import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Login from "./_components/login-button";
import { NextUIProvider } from "@nextui-org/react";
import { SessionProvider } from "next-auth/react";
import  {Providers}  from "src/app/_utils/provider";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        
        <TRPCReactProvider cookies={cookies().toString()}>
        <Providers>          
            
            {children}

          </Providers>

        </TRPCReactProvider>
      </body>
    </html>
  );
}



